name: Publish new release
#on:
#  push:
#    branches:
#      - main
#    paths:
#      - argparse.h

on: workflow_dispatch

jobs:
  new-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Get new version
      id: newVersion
      run: echo "value=v$(grep 'ARGPARSE_VERSION' argparse.h | sed 's/.*ARGPARSE_VERSION //')" >> "$GITHUB_OUTPUT"
    - name: Get old version
      id: oldVersion
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Print versions
      run: echo "${{ steps.oldVersion.outputs.tag }} => ${{ steps.newVersion.outputs.value }}"
    - name: Create release
      if: ${{ steps.oldVersion.outputs.tag != steps.newVersion.outputs.value }}
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.newVersion.outputs.value }}
        release_name: ${{ steps.newVersion.outputs.value }}
    - name: Create release asset
      if: ${{ steps.oldVersion.outputs.tag != steps.newVersion.outputs.value }}
      run: |
        make
        mv argparse-combined.h argparse.h
    - name: Upload release asset
      if: ${{ steps.oldVersion.outputs.tag != steps.newVersion.outputs.value }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: argparse.h
        asset_name: argparse.h
      
      
        
      
